### ISSUE TITLE
[BUG]: 500 error when loading customer usage

### ISSUE THREAD

**Issue by menecio** [getlago/lago-api#1262]
**Describe the bug**
After I added two more metrics to a plan and send some events in batch, I started getting a 500 error `TypeError (can't convert nil into BigDecimal)`

When I check the events from the developer page, I can see the events I've sent.

**To Reproduce**
1. Send some events
2. Go to the dashboard
3. Go to customer
4. Go to usage
5. Click on the plan to see the usage

**Expected behavior**

**Screenshots**
![image](https://github.com/getlago/lago-api/assets/924245/7625822e-e3fc-49aa-8249-66f584396cd1)

**Additional context**
Console logs:
```
lago-api     | I, [2023-08-22T09:14:30.663654 #11]  INFO -- : [974c16b8-6470-4e76-8c60-3325afe42c2b] {"method":"POST","path":"/graphql","format":"*/*","controller":"GraphqlController","action":"execute","status":500,"duration":61.9,"view":0.0,"db":20.88,"ddsource":"ruby","params":{"operationName":"customerUsage","variables":{"customerId":"__REPLACED__","subscriptionId":"9a7fa4d7-9953-4927-8da7-0f0b7987adf3"},"query":"query customerUsage($customerId: ID!, $subscriptionId: ID!) {\n  customerUsage(customerId: $customerId, subscriptionId: $subscriptionId) {\n    amountCents\n    currency\n    fromDatetime\n    toDatetime\n    chargesUsage {\n      units\n      amountCents\n      billableMetric {\n        id\n        code\n        name\n        __typename\n      }\n      __typename\n    }\n    ...CustomerUsageForUsageDetails\n    __typename\n  }\n}\n\nfragment CustomerUsageForUsageDetails on CustomerUsage {\n  fromDatetime\n  toDatetime\n  chargesUsage {\n    billableMetric {\n      name\n      __typename\n    }\n    groups {\n      id\n      amountCents\n      key\n      units\n      value\n      __typename\n    }\n    __typename\n  }\n  __typename\n}"},"sql_queries":"'User Load (0.56) SELECT \"users\".* FROM \"users\" WHERE \"users\".\"id\" = $1 LIMIT $2\nOrganization Load (0.85) SELECT \"organizations\".* FROM \"organizations\" INNER JOIN \"memberships\" ON \"organizations\".\"id\" = \"memberships\".\"organization_id\" WHERE \"memberships\".\"user_id\" = $1 AND \"organizations\".\"id\" = $2 LIMIT $3\nMembership Load (0.63) SELECT \"memberships\".* FROM \"memberships\" WHERE \"memberships\".\"organization_id\" = $1 AND \"memberships\".\"user_id\" = $2 LIMIT $3\nOrganization Pluck (1.45) SELECT \"organizations\".\"id\" FROM \"organizations\" INNER JOIN \"memberships\" ON \"organizations\".\"id\" = \"memberships\".\"organization_id\" WHERE \"memberships\".\"user_id\" = $1\nCustomer Load (0.59) SELECT \"customers\".* FROM \"customers\" WHERE \"customers\".\"deleted_at\" IS NULL AND \"customers\".\"id\" = $1 AND \"customers\".\"organization_id\" = $2 LIMIT $3\nSubscription Load (1.02) SELECT \"subscriptions\".* FROM \"subscriptions\" WHERE \"subscriptions\".\"customer_id\" = $1 AND \"subscriptions\".\"status\" = $2 AND \"subscriptions\".\"id\" = $3 ORDER BY \"subscriptions\".\"started_at\" DESC LIMIT $4\nEvent Load (1.78) SELECT \"events\".* FROM \"events\" WHERE \"events\".\"deleted_at\" IS NULL AND \"events\".\"subscription_id\" = $1 ORDER BY \"events\".\"created_at\" DESC LIMIT $2\nPlan Load (1.3) SELECT \"plans\".* FROM \"plans\" WHERE \"plans\".\"id\" = $1 LIMIT $2\nCustomer Load (0.46) SELECT \"customers\".* FROM \"customers\" WHERE \"customers\".\"id\" = $1 LIMIT $2\nOrganization Load (0.49) SELECT \"organizations\".* FROM \"organizations\" WHERE \"organizations\".\"id\" = $1 LIMIT $2\nInvoiceSubscription Load (1.38) SELECT \"invoice_subscriptions\".* FROM \"invoice_subscriptions\" WHERE \"invoice_subscriptions\".\"subscription_id\" = $1 ORDER BY             COALESCE(invoice_subscriptions.to_datetime, invoice_subscriptions.created_at) DESC\n LIMIT $2\nInvoice Load (0.4) SELECT \"invoices\".* FROM \"invoices\" WHERE \"invoices\".\"id\" = $1 LIMIT $2\nInvoiceSubscription Load (0.02) SELECT \"invoice_subscriptions\".* FROM \"invoice_subscriptions\" WHERE \"invoice_subscriptions\".\"subscription_id\" = $1 ORDER BY             COALESCE(invoice_subscriptions.to_datetime, invoice_subscriptions.created_at) DESC\n LIMIT $2\nInvoice Load (0.01) SELECT \"invoices\".* FROM \"invoices\" WHERE \"invoices\".\"id\" = $1 LIMIT $2\nOrganization Load (0.72) SELECT \"organizations\".* FROM \"organizations\" INNER JOIN \"customers\" ON \"organizations\".\"id\" = \"customers\".\"organization_id\" WHERE \"customers\".\"id\" = $1 LIMIT $2\nInvoiceSubscription Load (0.02) SELECT \"invoice_subscriptions\".* FROM \"invoice_subscriptions\" WHERE \"invoice_subscriptions\".\"subscription_id\" = $1 ORDER BY             COALESCE(invoice_subscriptions.to_datetime, invoice_subscriptions.created_at) DESC\n LIMIT $2\nInvoice Load (0.01) SELECT \"invoices\".* FROM \"invoices\" WHERE \"invoices\".\"id\" = $1 LIMIT $2\nCharge Load (4.69) SELECT \"charges\".* FROM \"charges\" INNER JOIN \"billable_metrics\" ON \"billable_metrics\".\"id\" = \"charges\".\"billable_metric_id\" WHERE \"charges\".\"deleted_at\" IS NULL AND \"charges\".\"plan_id\" = $1 ORDER BY lower(unaccent(billable_metrics.name)) ASC\nInvoiceSubscription Load (0.02) SELECT \"invoice_subscriptions\".* FROM \"invoice_subscriptions\" WHERE \"invoice_subscriptions\".\"subscription_id\" = $1 ORDER BY             COALESCE(invoice_subscriptions.to_datetime, invoice_subscriptions.created_at) DESC\n LIMIT $2\nInvoice Load (0.01) SELECT \"invoices\".* FROM \"invoices\" WHERE \"invoices\".\"id\" = $1 LIMIT $2\nGroupProperty Load (0.88) SELECT \"group_properties\".* FROM \"group_properties\" WHERE \"group_properties\".\"deleted_at\" IS NULL AND \"group_properties\".\"charge_id\" = $1\nGroupProperty Load (0.35) SELECT \"group_properties\".* FROM \"group_properties\" WHERE \"group_properties\".\"deleted_at\" IS NULL AND \"group_properties\".\"charge_id\" = $1 AND \"group_properties\".\"group_id\" IS NULL LIMIT $2\nBillableMetric Load (0.35) SELECT \"billable_metrics\".* FROM \"billable_metrics\" WHERE \"billable_metrics\".\"id\" = $1 LIMIT $2\nEvent Sum (2.26) SELECT SUM((events.properties->>'compute_units')::numeric) FROM \"events\" WHERE \"events\".\"deleted_at\" IS NULL AND \"events\".\"subscription_id\" = $1 AND (events.timestamp::timestamp(0) >= '2023-08-22 00:00:00') AND (events.timestamp::timestamp(0) <= '2023-08-31 23:59:59.999999') AND \"events\".\"code\" = $2 AND (events.properties->>'compute_units' IS NOT NULL)\nEvent Load (0.63) SELECT \"events\".* FROM \"events\" WHERE \"events\".\"deleted_at\" IS NULL AND \"events\".\"subscription_id\" = $1 AND (events.timestamp::timestamp(0) >= '2023-08-22 00:00:00') AND (events.timestamp::timestamp(0) <= '2023-08-31 23:59:59.999999') AND \"events\".\"code\" = $2 AND (events.properties->>'compute_units' IS NOT NULL) ORDER BY \"events\".\"created_at\" DESC LIMIT $3'","sql_queries_count":25}
lago-api     | F, [2023-08-22T09:14:30.664814 #11] FATAL -- : [974c16b8-6470-4e76-8c60-3325afe42c2b]
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] TypeError (can't convert nil into BigDecimal):
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b]
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/billable_metrics/aggregations/base_service.rb:66:in `BigDecimal'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/billable_metrics/aggregations/base_service.rb:66:in `handle_in_advance_current_usage'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/billable_metrics/aggregations/sum_service.rb:13:in `aggregate'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/fees/charge_service.rb:99:in `compute_amount'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/fees/charge_service.rb:56:in `init_fee'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/fees/charge_service.rb:46:in `init_fees'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/fees/charge_service.rb:30:in `current_usage'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/invoices/customer_usage_service.rb:71:in `block in add_charge_fees'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/invoices/customer_usage_service.rb:68:in `add_charge_fees'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/invoices/customer_usage_service.rb:44:in `block in compute_usage'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/invoices/customer_usage_service.rb:36:in `compute_usage'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/services/invoices/customer_usage_service.rb:26:in `usage'
lago-api     | [974c16b8-6470-4e76-8c60-3325afe42c2b] app/graphql/resolvers/customers/usage_resolver.rb:18:in `resolve'
```

**Version**
- Lago: v0.44.1-beta

**Comment by menecio** [comment]
The issue happens when the plan includes a metric that is charged by package in advance

**Comment by menecio** [comment]
Hi @lovrocolic as mentioned on slack, I'm not using the batch events endpoint and actually using the events endpoint, thus I don't think that's the issue here. 

Can we reopen this ticket please?
