### ISSUE TITLE
[BUG]: Initial user signup fails with: undefined method `invoice_grace_period` (v0.17.1-alpha)

### ISSUE THREAD

**Issue by gardner** [getlago/lago-api#661]
**Describe the bug**

```
lago-api  | I, [2022-12-10T02:18:51.180551 #14]  INFO -- sentry: [Transport] Sending envelope with items [event, client_report] 0132c44f88fb405583bbae7ed7c2d214 to Sentry
lago-api  | I, [2022-12-10T02:18:51.359917 #14]  INFO -- : [5822e624-94d7-4b1e-a9fa-b6978d04c78d] {"method":"POST","path":"/graphql","format":"*/*","controller":"GraphqlController","action":"execute","status":500,"duration":41.62,"view":0.0,"db":0.56,"ddsource":"ruby","params":{"operationName":"signup","variables":{"input":{"email":"jane@example.com","password":"[FILTERED]","organizationName":"Banco"}},"query":"mutation signup($input: RegisterUserInput!) {\n  registerUser(input: $input) {\n    token\n    user {\n      ...CurrentUser\n      __typename\n    }\n    organization {\n      id\n      name\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CurrentUser on User {\n  id\n  email\n  organizations {\n    ...CurrentOrganization\n    __typename\n  }\n  __typename\n}\n\nfragment CurrentOrganization on Organization {\n  id\n  name\n  logoUrl\n  ...ApiKeyOrganization\n  ...VatRateOrganization\n  __typename\n}\n\nfragment ApiKeyOrganization on Organization {\n  id\n  apiKey\n  __typename\n}\n\nfragment VatRateOrganization on Organization {\n  id\n  vatRate\n  __typename\n}","graphql":{"operationName":"signup","variables":{"input":{"email":"jane@example.com","password":"[FILTERED]","organizationName":"Banco"}},"query":"mutation signup($input: RegisterUserInput!) {\n  registerUser(input: $input) {\n    token\n    user {\n      ...CurrentUser\n      __typename\n    }\n    organization {\n      id\n      name\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CurrentUser on User {\n  id\n  email\n  organizations {\n    ...CurrentOrganization\n    __typename\n  }\n  __typename\n}\n\nfragment CurrentOrganization on Organization {\n  id\n  name\n  logoUrl\n  ...ApiKeyOrganization\n  ...VatRateOrganization\n  __typename\n}\n\nfragment ApiKeyOrganization on Organization {\n  id\n  apiKey\n  __typename\n}\n\nfragment VatRateOrganization on Organization {\n  id\n  vatRate\n  __typename\n}"}},"sql_queries":"'User Load (0.56) SELECT \"users\".* FROM \"users\" WHERE \"users\".\"email\" = $1 LIMIT $2'","sql_queries_count":1}
lago-api  | F, [2022-12-10T02:18:51.362386 #14] FATAL -- : [5822e624-94d7-4b1e-a9fa-b6978d04c78d]   
lago-api  | [5822e624-94d7-4b1e-a9fa-b6978d04c78d] NoMethodError (undefined method `invoice_grace_period' for #<Organization id: nil, name: "Banco", created_at: nil, updated_at: nil, api_key: nil, webhook_url: nil, vat_rate: 0.0, country: nil, address_line1: nil, address_line2: nil, state: nil, zipcode: nil, email: nil, city: nil, logo: nil, legal_name: nil, legal_number: nil, invoice_footer: nil>
lago-api  | Did you mean?  invoice_footer_changed?):
lago-api  | [5822e624-94d7-4b1e-a9fa-b6978d04c78d]   
lago-api  | [5822e624-94d7-4b1e-a9fa-b6978d04c78d] app/models/concerns/organization_timezone.rb:7:in `method_missing'
lago-api  | [5822e624-94d7-4b1e-a9fa-b6978d04c78d] app/services/users_service.rb:29:in `block in register'
lago-api  | [5822e624-94d7-4b1e-a9fa-b6978d04c78d] app/services/users_service.rb:28:in `register'
lago-api  | [5822e624-94d7-4b1e-a9fa-b6978d04c78d] app/graphql/mutations/register_user.rb:14:in `resolve'
```

**To Reproduce**
1. Follow steps here: https://doc.getlago.com/docs/guide/self-hosting/docker
2. Attempt to sign up.
3. Please note the error displayed in the UI
4. Please note the response from the graphql api: `{"status":500,"error":"Internal Server Error"}`
5. Please note the lago-api console log shows a stack dump.

**Expected behavior**
No stack dump

**Version**
- Lago: v0.17.1-alpha

**Comment by gardner** [comment]
Switching the version of docker containers to v0.16.x resolves this error.

**Comment by vincent-pochet** [comment]
Hi @gardner thank you for reporting this issue.

It seems that a recently added field `invoice_grace_period` is missing on the organizations table.
Could you try to run the migration process manually?

```bash
docker-compose exec api bundle exec rails db:migrate
```

**Comment by sarkissianraffi** [comment]
Hi @gardner, have you managed to perform this migration to get this new field? It's related to a feature called `grace periods`. If yes, I'll close this issue. Thanks a ton

**Comment by gardner** [comment]
It's a fresh install. Should we update the docs to include running the migrations? Cheers

**Comment by gardner** [comment]
I just re-tested it from scratch and I am unable to reproduce the issue. Sorry for the noise.

```
git clone https://github.com/getlago/lago.git
cd lago

echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env
source .env

FRONT_PORT=8881 API_PORT=3333 LAGO_API_URL=http://localhost:3333 docker-compose up
```
